In [1]:
import sqlite3
import pandas as pd

DB_PATH = "../data/cookie_cats.db"
conn = sqlite3.connect(DB_PATH)

In [2]:
# Read the SQL file
with open("../sql/02_build_analysis_view.sql", "r") as f:
    sql_script = f.read()

# Execute it (SQLite needs executescript for multiple statements)
conn.executescript(sql_script)
conn.commit()
print("View created successfully")

View created successfully

In [3]:
query = "SELECT COUNT(*) AS rows_in_view FROM analysis_view"
pd.read_sql(query, conn)

   rows_in_view
0         90189

In [4]:

query = "SELECT * FROM analysis_view LIMIT 5"
pd.read_sql(query, conn)

,userid,version,sum_gamerounds,retention_1,retention_7,retention_1_int,retention_7_int,is_outlier,engagement_segment
0,116,gate_30,3,0,0,0,0,0,light
1,337,gate_30,38,1,0,1,0,0,medium
2,377,gate_40,165,1,0,1,0,0,heavy
3,483,gate_40,1,0,0,0,0,0,light
4,488,gate_40,179,1,1,1,1,0,heavy

In [5]:
query = """
SELECT
    engagement_segment,
    COUNT(*) AS users,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS pct
FROM analysis_view
GROUP BY engagement_segment
ORDER BY users DESC
"""
pd.read_sql(query, conn)

  engagement_segment  users    pct
0              light  31995  35.48
1             medium  31388  34.80
2              heavy  17589  19.50
3         power_user   5223   5.79
4       never_played   3994   4.43

In [6]:
query = """
SELECT
    is_outlier,
    COUNT(*) AS users,
    MIN(sum_gamerounds) AS min_rounds,
    MAX(sum_gamerounds) AS max_rounds
FROM analysis_view
GROUP BY is_outlier
"""
pd.read_sql(query, conn)

   is_outlier  users  min_rounds  max_rounds
0           0  90188           0        2961
1           1      1       49854       49854